name: Commit-CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    container: strikef/swpp-ci
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile
        run: |
          cmake -GNinja -Bbuild
          ninja -Cbuild
      - name: Test
        run: |
          ninja -Cbuild test
      
    
