name: Commit-CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    container: strikef/swpp-ci
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: compile
        run: |
          cmake -GNinja -Bbuild
          cmake --build build --target swpp-compiler
        
      - name: test
        run: |
          cd build
          ctest
      
    
