name: Commit-CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/willi19/swpp202301-compiler-team6/swpp202301
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: compile
        run: |
          cmake -GNinja -Bbuild
          cmake --build build --target swpp-compiler
        
      - name: file-check
        run: |
           ./checkfile.sh /opt/llvm/bin/FileCheck
      
    
