# This workflow was written according to 
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Create and publish a Docker image
on:
  push:
    branches: [ 'update_docker' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name : install-ninja
        - uses: seanmiddleditch/gha-setup-ninja@master
        run: |
          mkdir build
          cd build
          cmake -G Ninja ..
        run: cmake --build build
      
      - name : install-alive2
        run : ./install-alive2.sh

      - name: build and publish
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          push: true
          tags: ghcr.io/willi19/swpp202301-compiler-team6/swpp202301:latest